name: "Type Check"
on: workflow_call
jobs:
  type-check:
    name: "Type Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: |
          corepack enable
      - name: Yarn Install
        run: yarn install --immutable
      - run: yarn tchk
